[package]
name = "zkwasm-rust-fibonacci"
description = "zkwasm rust fibonacci"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.87"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
test = []
